<?php

/**
 * @file
 * Adds contextual links to perform actions related to elements on a page.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 *
 * This shows 2 different ways you could show announcement from the toolbar.
 * 1 as a toolbar tray and 1 as link using off-canvas. You would not need both
 * ways.
 */
function announce_toolbar() {
  $items = [];
  $items['announce_off_canvas'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];
  $items['announce_tray'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  if (!\Drupal::currentUser()->hasPermission('access announce link')) {
    return $items;
  }

  $items['announce_off_canvas'] += [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Alerts(off-canvas)'),
      // @todo Create route to list items.
      '#url' => Url::fromRoute('system.admin'),
      '#attributes' => [
        'title' => t('Announce'),
        'class' => ['toolbar-icon', 'toolbar-icon-shortcut', 'use-ajax'],
        'data-dialog-renderer' => 'off_canvas',
        'data-dialog-type' => 'dialog',
        'data-dialog-options' => '{"width":"30%"}',
      ],
      '#attached' => [
        'library' => [
          'core/drupal.dialog.ajax',
        ],
      ],

    ],
    '#wrapper_attributes' => [
      'class' => ['announce-toolbar-tab'],
    ],
    '#weight' => 3399,
  ];

  $items['announce_tray'] += [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Alerts(tray)'),
      '#url' => Url::fromRoute('system.admin'),
      '#attributes' => [
        'title' => t('Announce'),
        'class' => ['toolbar-icon', 'toolbar-icon-shortcut'],
      ],
    ],
    '#wrapper_attributes' => [
      'class' => ['announce-toolbar-tab'],
    ],
    'tray' => [
      // @todo using lazy loading for actual items
      // @see user_toolbar()
      '#markup' => '<h1>Tester</h1>'
    ],
    '#weight' => 3399,
  ];
  return $items;
}

/**
 * Implements hook_theme().
 */
function announce_theme($existing, $type, $theme, $path) {
  return [
    'announce_list' => [
      'variables' => ['items' => NULL],
    ],
  ];
}
