<?php

/**
 * @file
 * Adds contextual links to perform actions related to elements on a page.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function announce_toolbar() {
  $items = [];
  $items['announce'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  if (!\Drupal::currentUser()->hasPermission('access announce link')) {
    return $items;
  }
  $data = [];
  $client = \Drupal::httpClient();
  // $host = \Drupal::request()->getHost();
  try {
    // $response = $client->get($host . '/community-aanounce.php');.
    $response = $client->get('https://my-json-server.typicode.com/haris-m-aslam/demo-json/posts');
    $result = $response->getBody();
    $data = json_decode($result, TRUE);
  }
  catch (RequestException $e) {
    watchdog_exception('my_module', $e->getMessage());
  }

  $items['announce'] += [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Alerts'),
      '#url' => Url::fromRoute('system.admin'),
      '#attributes' => [
        'title' => t('Announce'),
        'class' => ['toolbar-icon', 'toolbar-icon-shortcut', 'use-ajax'],
        'data-dialog-renderer' => 'off_canvas',
        'data-dialog-type' => 'dialog',
        'data-dialog-options' => '{"width":"30%"}',
      ],
      '#attached' => [
        'library' => [
          'core/drupal.dialog.ajax',
        ],
      ],

    ],
    'tray' => [
      '#markup' => '<h1>hello</h1>',
    ],
    '#wrapper_attributes' => [
      'class' => ['announce-toolbar-tab'],
    ],
    '#weight' => 3399,
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function announce_theme($existing, $type, $theme, $path) {
  return [
    'announce_list' => [
      'variables' => ['items' => NULL],
    ],
  ];
}
